site_name: Orchard Core 中文文档
theme:
  name: material
  logo: docs/assets/images/orchard-logo.png
  favicon: docs/assets/images/favicon-blue.png
  features:
    - instant
    - tabs
  palette:
    primary: blue
    accent: light blue
  static_templates:
    - docs/404.html
    
extra:
  social:
    - icon: fontawesome/solid/leaf
      link: https://orchardcore.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/OrchardCMS/OrchardCore
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OrchardCMS

# Repository
repo_name: OrchardCoreCn/OrchardCore
repo_url: https://github.com/OrchardCoreCn/OrchardCore
edit_uri: edit/dev/src/

# Options
docs_dir: src

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.b64
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
#  - markdown.extensions.nl2br

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        # Excluding the large node folder with all its MD files. We can't exclude everything apart from docs because there are links to e.g. C# files too.
        - "*node_modules*"
  
# Page tree
nav:
    - 关于 Orchard Core: README.md
    - 入门: 
        - 创建一个Web应用程序: docs/getting-started/README.md
        - 配置预览包源: docs/getting-started/preview-package-source.md
        - 食谱和入门主题: docs/getting-started/starter-recipes.md
        - 代码生成模板: docs/getting-started/templates/README.md
        - 创建一个主题: docs/getting-started/theme.md
    - 词汇表: 
        - 术语和概念: docs/glossary/README.md
    - 入门指南: 
        - 遵循指南: docs/guides/README.md
        - 创建一个模块化应用程序: docs/guides/create-modular-application-mvc/README.md
        - 创建一个网站: docs/guides/create-cms-application/README.md
        - 创建一个已解耦的CMS站点: docs/guides/decoupled-cms/README.md
        - 添加管理菜单: docs/guides/add-admin-menu/README.md
        - 实现全文搜索: docs/guides/implement-fulltext-search/README.md
        - 安装本地化文件: docs/guides/install-localization-files/README.md
        - 集成Facebook插件: docs/guides/integrate-facebook-plugins/README.md
        - Startup 配置: docs/guides/run-code-on-startup/README.md
        - 创建自定义管理主题: docs/guides/create-admin-theme/README.md
        - 自定义编码设置: docs/guides/encoding-settings/README.md
    - 关键主题: 
        - 管理您的内容: docs/topics/content-management/README.md
        - 自定义显示: docs/topics/display/README.md
        - 本地化您的网站: docs/topics/localize/README.md
        - 处理媒体: docs/topics/media/README.md
        - 在页面之间导航: docs/topics/navigation/README.md
        - 查询和搜索数据: docs/topics/search/README.md
        - 保护您的应用程序: docs/topics/security/README.md
#        - 数据: docs/topics/data/README.md
#        - 配置: docs/topics/configuration/README.md
        - 工作流: docs/topics/workflows/README.md
        - 为文档做贡献: docs/topics/docs-contributions/README.md
    - 参考资料: 
        - CMS模块: 
            - 内容类型(Content Types): docs/reference/modules/ContentTypes/README.md
            - 内容部件(Content Parts): 
                - 将部件添加到您的内容: docs/reference/modules/ContentParts/README.md
                - Title: docs/reference/modules/Title/README.md
                - Autoroute: docs/reference/modules/Autoroute/README.md
                - Alias: docs/reference/modules/Alias/README.md
                - Html: docs/reference/modules/Html/README.md
                - Markdown: docs/reference/modules/Markdown/README.md
                - List: docs/reference/modules/List/README.md
                - Flow: docs/reference/modules/Flow/README.md 
                - Bag: docs/reference/modules/Flow/BagPart.md
                - Publish Later: docs/reference/modules/PublishLater/README.md
            - Content Fields: docs/reference/modules/ContentFields/README.md
            - Content Preview: docs/reference/modules/ContentPreview/README.md
            - Content Localization: docs/reference/modules/ContentLocalization/README.md
            - Layers: docs/reference/modules/Layers/README.md
            - Widgets: docs/reference/modules/Widgets/README.md
            - Forms: docs/reference/modules/Forms/README.md
            - Templates: docs/reference/modules/Templates/README.md
            - Themes: docs/reference/modules/Themes/README.md
            - Liquid: docs/reference/modules/Liquid/README.md
            - Indexing: docs/reference/modules/Indexing/README.md
            - SQL: docs/reference/modules/SQL/README.md
            - Lucene: docs/reference/modules/Lucene/README.md
            - Queries: docs/reference/modules/Queries/README.md
            - Media: docs/reference/modules/Media/README.md
            - Media Azure: docs/reference/modules/Media.Azure/README.md
            - ReCaptcha: docs/reference/modules/ReCaptcha/README.md
            - Resources: docs/reference/modules/Resources/README.md
            - ShortCodes: docs/reference/modules/ShortCodes/README.md
            - Sitemaps: docs/reference/modules/Sitemaps/README.md
            - XML-RPC: docs/reference/modules/XmlRpc/README.md
            - Menu: docs/reference/modules/Menu/README.md
            - Navigation: docs/reference/modules/Navigation/README.md
            - Admin: docs/reference/modules/Admin/README.md
            - Admin Menu: docs/reference/modules/AdminMenu/README.md
            - Taxonomies: docs/reference/modules/Taxonomies/README.md
            - Authentication:
                - Microsoft: docs/reference/modules/Microsoft.Authentication/README.md
                - Facebook: docs/reference/modules/Facebook/README.md
                - Twitter: docs/reference/modules/Twitter/README.md
                - GitHub: docs/reference/modules/GitHub/README.md
                - Google: docs/reference/modules/Google/README.md
            - Users: docs/reference/modules/Users/README.md
        - Core Modules: 
    #        - How to use Core Modules: docs/reference/core/README.md
            - 功能: docs/reference/modules/Features/README.md
            - 内容: docs/reference/modules/Contents/README.md
            - 配置: docs/reference/core/Configuration/README.md
            - 自定义设置: docs/reference/modules/CustomSettings/README.md
            - Placement: docs/reference/core/Placement/README.md
            - Data: docs/reference/core/Data/README.md
            - 动态缓存 Cache: docs/reference/modules/DynamicCache/README.md
            - 电子邮件: docs/reference/modules/Email/README.md
            - GraphQL: docs/reference/modules/Apis.GraphQL/README.md
            - GraphQL queries: docs/reference/core/Apis.GraphQL.Abstractions/README.md
            - Health Check: docs/reference/modules/HealthChecks/README.md
            - HTTPS: docs/reference/modules/Https/README.md
            - 本地化: docs/reference/modules/Localize/README.md
            - 记录日志: docs/reference/core/Logging.Serilog/readme.md
            - Mini Profiler: docs/reference/modules/MiniProfiler/README.md
            - 模块: docs/reference/core/Modules/README.md
            - OpenId: docs/reference/modules/OpenId/README.md
            - Razor Helpers: docs/reference/core/Razor/README.md
            - 食谱: docs/reference/modules/Recipes/README.md
            - 响应压缩: docs/reference/modules/ResponseCompression/README.md
            - 角色: docs/reference/modules/Roles/README.md
            - 脚本编写: docs/reference/modules/Scripting/README.md
            - 安装: docs/reference/modules/Setup/README.md
            - Shells: docs/reference/core/Shells/README.md
            - 多租户: docs/reference/modules/Tenants/README.md
            - 工作流: docs/reference/modules/Workflows/README.md
            - 数据保护 (Azure存储): docs/reference/modules/DataProtection.Azure/README.md
    - 资源: 
        - 学习: docs/resources/README.md
        - 工作坊: docs/resources/workshops/README.md
        - 品牌: docs/resources/branding/README.md
    - 发布: 
        - 1.0.0-rc2: docs/releases/1.0.0-rc2.md
        - 1.0.0-rc1: docs/releases/1.0.0-rc1.md
        - 1.0.0-beta3: docs/releases/1.0.0-beta3.md
        - 1.0.0-beta2: docs/releases/1.0.0-beta2.md
        - 1.0.0-beta1: docs/releases/1.0.0-beta1.md
    
